<?php
$title='My tests';
?>
<h1><?php echo $this->escapeHtml($title);?></h1>
<p>
    <a href="<?php echo $this->url('test',array('action'=>'add'));?>">Add new test</a>
    <a href="<?php echo $this->url('test',array('action'=>'join'));?>">Join</a>
</p>

<table class="table">
    <tr>
        <th>Student</th>
        <th>Grade</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($tests as $test):?>
    <tr>
        <td><?php echo $this->escapeHtml($test->student);?></td>
        <td><?php echo $this->escapeHtml($test->grade);?></td>
    </tr>
    <?php endforeach;?>
</table>
