<?php
$title='Join test';
?>
<h1><?php echo $this->escapeHtml($title);?></h1>

<table class="table">
    <tr>
        <th>Student</th>
        <th>Grade</th>
        <th>Title</th>
        <th>Artist</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($results as $result):?>
    <tr>
        <td><?php echo $this->escapeHtml($result->student);?></td>
        <td><?php echo $this->escapeHtml($result->grade);?></td>
        <td><?php echo $this->escapeHtml($result->title);?></td>
        <td><?php echo $this->escapeHtml($result->artist);?></td>
    </tr>
    <?php endforeach?>
</table>
